[package]
name = "threading_in_local"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
futures = "0.3.25"
crossbeam-utils = "0.8.14"
scopeguard = "1.1.0"
