/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class App */

#ifndef _Included_App
#define _Included_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     App
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_App_mul
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     App
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_App_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
